### ISSUE TITLE
fix back references when first class is extended

### ISSUE THREAD

**Issue by Baumgaer** [Baumgaer/boilerplate#55]
## The scenario

```typescript
import { Attr, Model } from "~client/utils/decorators";
import CommonExample from "~common/models/Example";
import type ExampleParams from "~client/interfaces/models/Example";
import type YetAnotherExample from "~client/models/YetAnotherExample";

@Model()
export default class Example extends CommonExample {

    @Attr({ relationColumn: "oneToManyRelation" })
    public manyToOneRelation!: YetAnotherExample;

    public constructor(params?: ExampleParams) {
        super(params);
    }
}
```

```typescript
import { Attr, Model } from "~client/utils/decorators";
import Examplefrom "~client/models/Example";
import type AnotherExampleParams from "~client/interfaces/models/AnotherExample";

@Model()
export default class AnotherExample extends Example{

    @Attr()
    public myUnion: "test" | 42 = 42;

    @Attr()
    public anotherExampleClient!: Lazy<number[]>;

    public constructor(params?: AnotherExampleParams) {
        super(params);
    }
}
```

```typescript
import { Attr, Model } from "~client/utils/decorators";
import CommonYetAnotherExample from "~common/models/YetAnotherExample";
import type YetAnotherExampleParams from "~client/interfaces/models/YetAnotherExample";
import type Example from "~client/models/Example";

@Model()
export default class YetAnotherExample extends CommonYetAnotherExample {

    @Attr({ relationColumn: "manyToOneRelation", isRelationOwner: true })
    public oneToManyRelation?: Example[];

    public constructor(params?: YetAnotherExampleParams) {
        super(params);
    }
}
```

## The Problem

When **AnotherExample** is initialized with correct parameters and it should be saved, typeORM will throw an error as follows:

```
Uncaught (in promise) TypeORMError: Cyclic dependency: "YetAnotherExample"
    at visit (SubjectTopoligicalSorter.js:144:1)
    at visit (SubjectTopoligicalSorter.js:161:1)
    at visit (SubjectTopoligicalSorter.js:161:1)
    at SubjectTopoligicalSorter.toposort (SubjectTopoligicalSorter.js:140:1)
    at SubjectTopoligicalSorter.sort (SubjectTopoligicalSorter.js:50:1)
    at SubjectExecutor.execute (SubjectExecutor.js:88:59)
    at EntityPersistExecutor.execute (EntityPersistExecutor.js:145:1)
```

The reason for this is that **YetAnotherExample** creates a back reference to **Example**, not to **AnotherExample**. When an instance of **Example** will be saved, this works fine.

## The solution

When building the relation, we have to check if there is a derived class of the back reference. If so, we have to throw a hint to the developer. If the back reference includes both types separately as a union, this should be ok. The shema type has to take care of this.

**Comment by Baumgaer** [comment]
TypeORM actually has already a solution. When Models have shared attributes, the have to be derived from a pseudomodel which does not register the model as an entity in typeORM. For this, we will introduce a new option called "isPseudo" to achieve this behavior. Therefore models in common environment should always be a pseudo model.

**Comment by Baumgaer** [comment]
Sadly this is not a solution because relations are not working with concrete inheritance. So we have to implement this for our use case.
